# Generated by Django 4.2.6 on 2023-10-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='credit',
            field=models.IntegerField(blank=True, null=True, verbose_name='クレジットカード情報'),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_shop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='お気に入り'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_review',
            field=models.TextField(blank=True, null=True, verbose_name='レビュー'),
        ),
        migrations.AlterField(
            model_name='member',
            name='reservedshop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='予約店舗'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='budget',
            field=models.PositiveIntegerField(verbose_name='予算(円)'),
        ),
    ]
