# Generated by Django 4.2.6 on 2023-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='parking',
            field=models.BooleanField(default=1, verbose_name='駐車場'),
            preserve_default=False,
        ),
    ]
