# Generated by Django 4.2.6 on 2023-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='名前'),
        ),
    ]
