# Generated by Django 4.2.6 on 2023-10-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0002_alter_member_credit_alter_member_favorite_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='credit',
        ),
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='カード番号'),
        ),
        migrations.AddField(
            model_name='member',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='クレジットカード情報'),
        ),
        migrations.AddField(
            model_name='member',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='有効期限'),
        ),
    ]
