# Generated by Django 4.2.6 on 2023-12-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0002_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid',
            field=models.BooleanField(default='', verbose_name='有料会員'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=10, verbose_name='パスワード'),
        ),
    ]
