# Generated by Django 4.2.6 on 2023-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='mysite/static/nagoyameshi/images/noImage.png', null=True, upload_to='', verbose_name='写真'),
        ),
    ]
