# Generated by Django 4.2.6 on 2023-10-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_remove_member_credit_member_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='review_shop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='レビューした店舗'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='クレジットカード登録名'),
        ),
    ]
