# Generated by Django 4.2.6 on 2023-12-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0004_alter_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='res_customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='members',
        ),
    ]
