# Generated by Django 4.2.6 on 2023-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0004_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=1, upload_to='shop_images/'),
            preserve_default=False,
        ),
    ]
