# Generated by Django 4.2.6 on 2023-11-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0005_remove_shop_parking_shop_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='conditions',
            field=models.CharField(blank=True, choices=[('ベジタリアン', 'ベジタリアン'), ('ビーガン', 'ビーガン'), ('日本酒', '日本酒'), ('個室', '個室'), ('座敷', '座敷'), ('掘りごたつ', '掘りごたつ'), ('食べ放題', '食べ放題'), ('飲み放題', '飲み放題'), ('駐車場', '駐車場')], max_length=50, verbose_name='こだわり条件'),
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ManyToManyField(blank=True, to='nagoyameshi.shop')),
            ],
        ),
    ]
