# Generated by Django 4.2.6 on 2023-12-25 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0005_remove_favorite_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='予約者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='有料会員'),
            preserve_default=False,
        ),
    ]
