# Generated by Django 4.2.6 on 2023-12-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0006_favorite_customer_reservation_res_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid',
            field=models.BooleanField(verbose_name='有料会員'),
        ),
    ]
