# Generated by Django 4.2.6 on 2023-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0006_alter_shop_conditions_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='conditions',
        ),
        migrations.AddField(
            model_name='shop',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.condition', verbose_name='こだわり条件'),
        ),
    ]
