# Generated by Django 4.2.6 on 2023-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0007_remove_condition_condition_remove_shop_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='CONDITIONS',
            field=models.CharField(choices=[('ベジタリアン', 'ベジタリアン'), ('ビーガン', 'ビーガン'), ('日本酒', '日本酒'), ('個室', '個室'), ('座敷', '座敷'), ('掘りごたつ', '掘りごたつ'), ('食べ放題', '食べ放題'), ('飲み放題', '飲み放題'), ('駐車場', '駐車場')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
