# Generated by Django 4.2.6 on 2023-12-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0007_alter_member_email_alter_member_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='paid',
        ),
    ]
