# Generated by Django 4.2.6 on 2023-12-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0008_remove_member_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=50, verbose_name='店休日')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='ジャンル')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='nosmoking',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_reservation',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='smokingbooth',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='sns',
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_max',
            field=models.PositiveIntegerField(default=1, verbose_name='予算(高)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_min',
            field=models.PositiveIntegerField(default=1, verbose_name='予算(安)'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='shop',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='genre',
        ),
        migrations.AddField(
            model_name='shop',
            name='day_of_week',
            field=models.ManyToManyField(to='nagoyameshi.dayofweek', verbose_name='店休日'),
        ),
        migrations.AddField(
            model_name='shop',
            name='genre',
            field=models.ManyToManyField(to='nagoyameshi.genre', verbose_name='ジャンル'),
        ),
    ]
