# Generated by Django 4.2.6 on 2023-11-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0008_condition_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='CONDITIONS',
            new_name='name',
        ),
    ]
