# Generated by Django 4.2.6 on 2023-11-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0009_rename_conditions_condition_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='name',
            new_name='CONDITIONS',
        ),
    ]
