# Generated by Django 4.2.6 on 2023-12-28 16:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0009_dayofweek_genre_remove_shop_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='cvv'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='money',
            field=models.PositiveIntegerField(default='300', verbose_name='売上'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='access',
            field=models.CharField(default='徒歩5分', max_length=100, verbose_name='アクセス'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(default='名古屋市', max_length=100, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='budget_max',
            field=models.PositiveIntegerField(default='10000', verbose_name='予算(高)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='budget_min',
            field=models.PositiveIntegerField(default='1000', verbose_name='予算(安)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(default='22:00', verbose_name='閉店時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='day_of_week',
            field=models.ManyToManyField(to='nagoyameshi.dayofweek', verbose_name='定休日'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='media_local/noImage.png', upload_to='media_local', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='neareststation',
            field=models.CharField(default='名古屋駅', max_length=50, verbose_name='最寄駅'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(default='7:00', verbose_name='開店時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='openingdate',
            field=models.DateField(default='1990-11-11', verbose_name='開業日'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01-2345-6789', max_length=128, region='JP', verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='seats',
            field=models.PositiveIntegerField(default='20', verbose_name='席数'),
        ),
    ]
