# Generated by Django 4.2.6 on 2023-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0010_rename_name_condition_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='conditions',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.AddField(
            model_name='shop',
            name='conditions',
            field=models.CharField(blank=True, choices=[('ベジタリアン', 'ベジタリアン'), ('ビーガン', 'ビーガン'), ('日本酒', '日本酒'), ('個室', '個室'), ('座敷', '座敷'), ('掘りごたつ', '掘りごたつ'), ('食べ放題', '食べ放題'), ('飲み放題', '飲み放題'), ('駐車場', '駐車場')], max_length=50, verbose_name='こだわり条件'),
        ),
    ]
