# Generated by Django 4.2.6 on 2024-01-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0010_alter_member_cvv_alter_sales_money_alter_shop_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, verbose_name='パスワード'),
        ),
    ]
