# Generated by Django 4.2.6 on 2023-11-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0011_remove_shop_conditions_delete_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='conditions',
            new_name='condition',
        ),
    ]
