# Generated by Django 4.2.6 on 2023-11-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0013_alter_shop_shop_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.shop', verbose_name='店舗'),
        ),
    ]
