# Generated by Django 4.2.6 on 2023-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0014_alter_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50, verbose_name='こだわり条件')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='privateroom',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='condition',
        ),
        migrations.AddField(
            model_name='shop',
            name='condition',
            field=models.ManyToManyField(to='nagoyameshi.condition', verbose_name='こだわり条件'),
        ),
    ]
