# Generated by Django 4.2.6 on 2023-11-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0014_alter_review_review_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_review',
        ),
    ]
