# Generated by Django 4.2.6 on 2023-11-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0015_condition_remove_shop_privateroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='condition',
            new_name='kodawari',
        ),
    ]
