# Generated by Django 4.2.6 on 2023-11-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0016_shop_shop_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_review',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nagoyameshi.review', verbose_name='レビュー'),
        ),
    ]
