# Generated by Django 4.2.6 on 2023-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0017_alter_shop_shop_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_review',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='レビュー'),
        ),
    ]
